const MAX={product:200,company:200,specification:2000,quantity:200,destination:200,timing:200,email:320,phone:80,message:4000,language:10};
const LANG=new Set(["en","ru","fa","ar","uz","tr"]);
const TYPES=new Set(["application/pdf","image/jpeg"]);
const MAX_FILE=1048576;
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=UTF-8","cache-control":"no-store"}});
const clean=(v,n)=>v==null?"":String(v).trim().slice(0,n);
const tooLong=(v,n)=>v!=null&&String(v).trim().length>n;
const year=()=>new Date().getUTCFullYear();
async function nextNo(db){const p=`AGZ-${year()}-`;const r=await db.prepare("SELECT MAX(CAST(SUBSTR(request_number,10) AS INTEGER)) sequence FROM inquiries WHERE request_number LIKE ?").bind(`${p}%`).first();return `${p}${String(Number(r?.sequence||0)+1).padStart(6,"0")}`;}
function b64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a;}
async function createInquiry(req,env){let b;try{b=await req.json()}catch{return json({error:"invalid_json"},400)}for(const k of Object.keys(MAX))if(tooLong(b?.[k],MAX[k]))return json({error:"field_too_long",field:k,max_length:MAX[k]},400);const language=LANG.has(b?.language)?b.language:"en",product=clean(b?.product,MAX.product),company=clean(b?.company,MAX.company),specification=clean(b?.specification,MAX.specification),quantity=clean(b?.quantity,MAX.quantity),destination=clean(b?.destination,MAX.destination),timing=clean(b?.timing,MAX.timing),email=clean(b?.email,MAX.email),phone=clean(b?.phone,MAX.phone),message=clean(b?.message,MAX.message);if(!product)return json({error:"product_required"},400);if(!email&&!phone)return json({error:"contact_required"},400);if(email&&!EMAIL.test(email))return json({error:"invalid_email"},400);if(!env.AGROZIA_DB)return json({error:"d1_unavailable"},503);let file=null;if(b?.attachment){const a=b.attachment,n=clean(a.name,180),t=clean(a.type,100),size=Number(a.size||0),raw=typeof a.data_base64==="string"?a.data_base64:"";if(!n||!TYPES.has(t)||!raw)return json({error:"invalid_attachment"},400);if(!Number.isInteger(size)||size<1||size>MAX_FILE)return json({error:"attachment_too_large",max_bytes:MAX_FILE},400);try{const data=b64(raw);if(data.byteLength!==size||data.byteLength>MAX_FILE)return json({error:"invalid_attachment_size"},400);file={n,t,size,data}}catch{return json({error:"invalid_attachment"},400)}}const created=new Date().toISOString();for(let i=0;i<6;i++){try{const no=await nextNo(env.AGROZIA_DB);const q=[env.AGROZIA_DB.prepare(`INSERT INTO inquiries (request_number,created_at,language,product,company,specification,quantity,destination,timing,email,phone,message,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'received')`).bind(no,created,language,product,company||null,specification||null,quantity||null,destination||null,timing||null,email||null,phone||null,message||null)];if(file)q.push(env.AGROZIA_DB.prepare("INSERT INTO inquiry_attachments (request_number,created_at,file_name,content_type,file_size,file_data) VALUES (?,?,?,?,?,?)").bind(no,created,file.n,file.t,file.size,file.data));await env.AGROZIA_DB.batch(q);return json({ok:true,persisted:true,attachment_received:Boolean(file),request_number:no,status:"received",created_at:created},201)}catch(e){if(String(e?.message||"").toLowerCase().includes("unique")&&i<5)continue;console.error("D1 inquiry persistence failed",e);return json({error:"d1_persistence_failed"},503)}}return json({error:"d1_persistence_failed"},503)}
async function assets(req,env){const r=await env.ASSETS.fetch(req),ct=r.headers.get("content-type")||"";if(!ct.includes("text/html"))return r;const u=new URL(req.url);if(!["/","/multilingual-preview","/multilingual-preview.html","/inquiry.html"].includes(u.pathname))return r;let h=await r.text();h=h.replace("</body>",'<script src="/inquiry-integration.js"></script>\n</body>');if(u.pathname==="/inquiry.html")h=h.replace('<script src="locales/language-selector.js"></script>','<script src="/inquiry-ux.js"></script>\n<script src="locales/language-selector.js"></script>');const heads=new Headers(r.headers);heads.delete("content-length");return new Response(h,{status:r.status,statusText:r.statusText,headers:heads})}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==="/api/inquiries"&&req.method==="POST")return createInquiry(req,env);if(u.pathname==="/api/health"&&req.method==="GET")return json({ok:true,service:"agro-zia-inquiry-api",d1_bound:Boolean(env.AGROZIA_DB)});return env.ASSETS?assets(req,env):new Response("Not Found",{status:404})}};
