/* Agro-Zia V3 multilingual preview — EN/RU/FA/AR/UZ/TR */
(function () {
  const languages = {
    en: { label: 'English', short: 'EN', dir: 'ltr' },
    ru: { label: 'Русский', short: 'RU', dir: 'ltr' },
    fa: { label: 'فارسی', short: 'فا', dir: 'rtl' },
    ar: { label: 'العربية', short: 'ع', dir: 'rtl' },
    uz: { label: 'O‘zbek', short: 'UZ', dir: 'ltr' },
    tr: { label: 'Türkçe', short: 'TR', dir: 'ltr' }
  };

  const t = {
    en: {
      nav_home:'Home', nav_about:'About', nav_products:'Products', nav_engineering:'Engineering', nav_projects:'Projects', nav_trade:'Trade', nav_knowledge:'Knowledge', nav_contact:'Contact',
      eyebrow:'AGRICULTURE • ENGINEERING • INTERNATIONAL TRADE', hero_title:'Agricultural Solutions Beyond Borders.', hero_lead:'Agricultural products, engineering expertise and international trade solutions connecting producers, suppliers and markets.', hero_primary:'Explore Our Solutions', hero_secondary:'Start a Business Inquiry',
      intro_title:'Connecting products, expertise and markets.', intro_text:'Agro-Zia is being developed as a professional B2B platform for agricultural products, technical services, projects and international business connections.',
      business_eyebrow:'OUR BUSINESS', business_title:'Four capabilities. One agricultural business platform.', business_text:'We connect products, technical expertise, project development and market opportunities around practical agricultural needs.',
      products:'Agricultural Products', products_text:'Fertilizers, agricultural inputs, production products and selected supply categories for professional buyers.', engineering:'Engineering', engineering_text:'Technical assessment, planning, irrigation, greenhouse and agricultural production solutions.', projects:'Projects', projects_text:'Project planning, technical coordination and supervision supported by appropriate specialists and partners.', trade:'International Trade', trade_text:'Sourcing, supplier–buyer connections and market development across regional and international opportunities.',
      products_title:'Selected supply categories for professional buyers.', products_note:'Product information and quotations are handled through business inquiries and verified supply details.', fertilizer:'Fertilizers', fertilizer_text:'Fertilizer categories and formulations selected according to crop, soil and market requirements.', inputs:'Agricultural Inputs', inputs_text:'Production inputs for agricultural operations, subject to product verification and availability.', ag_products:'Agricultural Products', ag_products_text:'A growing portfolio of agricultural products for domestic and international commercial partners.', greenhouse:'Greenhouse Products', greenhouse_text:'Selected greenhouse-related products and solutions for protected agriculture.', irrigation:'Irrigation & Equipment', irrigation_text:'Equipment and solutions for agricultural water management and production systems.', sourcing:'Custom Sourcing', sourcing_text:'Tell us what you need and we can evaluate sourcing and supply opportunities.', quote:'Request a Quote', info:'Request Information', inquiry:'Start an Inquiry',
      engineering_title:'Agricultural engineering with a practical focus.', engineering_text2:'Technical support for agricultural projects, production systems and infrastructure requirements.', greenhouse_dev:'Greenhouse Development', project_plan:'Agricultural Project Planning', irrigation_sol:'Irrigation Solutions', production:'Production Systems', assessment:'Technical Assessment', consulting:'Consulting',
      projects_title:'From technical challenge to practical solution.', projects_text:'Selected projects will be presented as case studies as verified project information becomes available.', case_framework:'CASE STUDY FRAMEWORK', context:'Location & Context', challenge:'Challenge & Solution', results:'Results & Evidence',
      markets_title:'Markets we connect.', market_note:'Target markets are presented as areas of commercial interest, not as claims of established operations unless verified.', iran:'Iran', uzbekistan:'Uzbekistan', turkiye:'Türkiye', iraq:'Iraq',
      network_title:'Zarus — Agricultural Supply Network', network_text:'Zarus is positioned as a connected agricultural supply platform, helping bring suppliers and agricultural customers together.', suppliers:'Suppliers', customers:'Agricultural Customers', network_link:'Explore the developing Zarus platform and its supplier–customer model.',
      why_title:'Technical thinking behind commercial opportunities.', experience:'Technical Experience', knowledge:'Agricultural Perspective', network:'Supplier Connections', outlook:'International Perspective',
      about_title:'Technical knowledge. Agricultural perspective. International outlook.', about_text:'Agro-Zia is being developed as a B2B platform connecting agricultural products, technical expertise and market opportunities.', partnerships:'Business Partnerships',
      knowledge_title:'Practical agricultural knowledge.', knowledge_text:'A future knowledge center for technical information, market insights and agricultural topics.', technology:'Agricultural Technology', fertilizers:'Fertilizers', greenhouse_management:'Greenhouse Management', market_insights:'Market Insights',
      contact_title:'Tell us what you are looking for.', contact_text:'Whether you need a product, engineering service, project partner or trade connection, send us your requirements.', name:'Name', company:'Company', country:'Country', email:'Email', phone:'WhatsApp / Phone', interest:'Interest', message:'Message', submit:'Submit Business Inquiry', form_note:'For this initial static release, submitting the form opens your email client. A server-side lead endpoint can be added in a later V3.x phase.',
      footer_explore:'Explore', footer_markets:'Markets', footer_contact:'Contact', footer_connect:'Connecting agricultural products, expertise and markets.'
    },
    ru: {
      nav_home:'Главная', nav_about:'О нас', nav_products:'Продукция', nav_engineering:'Инжиниринг', nav_projects:'Проекты', nav_trade:'Торговля', nav_knowledge:'Знания', nav_contact:'Контакты',
      eyebrow:'СЕЛЬСКОЕ ХОЗЯЙСТВО • ИНЖИНИРИНГ • МЕЖДУНАРОДНАЯ ТОРГОВЛЯ', hero_title:'Агропромышленные решения без границ.', hero_lead:'Сельскохозяйственная продукция, инженерная экспертиза и решения для международной торговли, соединяющие производителей, поставщиков и рынки.', hero_primary:'Наши решения', hero_secondary:'Отправить бизнес-запрос',
      intro_title:'Соединяем продукцию, экспертизу и рынки.', intro_text:'Agro-Zia развивается как профессиональная B2B-платформа для сельскохозяйственной продукции, технических услуг, проектов и международных деловых связей.',
      business_eyebrow:'НАШ БИЗНЕС', business_title:'Четыре направления. Одна аграрная бизнес-платформа.', business_text:'Мы объединяем продукцию, техническую экспертизу, развитие проектов и рыночные возможности вокруг практических задач сельского хозяйства.',
      products:'Сельскохозяйственная продукция', products_text:'Удобрения, аграрные ресурсы, продукция и выбранные категории поставок для профессиональных покупателей.', engineering:'Инжиниринг', engineering_text:'Техническая оценка, планирование, ирригация, теплицы и решения для сельскохозяйственного производства.', projects:'Проекты', projects_text:'Планирование, техническая координация и надзор при поддержке профильных специалистов и партнеров.', trade:'Международная торговля', trade_text:'Поиск поставщиков, связи между продавцами и покупателями и развитие рынков на региональном и международном уровне.',
      products_title:'Выбранные категории поставок для профессиональных покупателей.', products_note:'Информация о продукции и коммерческие предложения предоставляются через бизнес-запросы и после проверки поставок.', fertilizer:'Удобрения', fertilizer_text:'Категории и формуляции удобрений с учетом культуры, почвы и требований рынка.', inputs:'Сельскохозяйственные ресурсы', inputs_text:'Производственные ресурсы для сельского хозяйства с учетом проверки продукции и наличия.', ag_products:'Аграрная продукция', ag_products_text:'Развивающийся портфель продукции для внутренних и международных коммерческих партнеров.', greenhouse:'Тепличные решения', greenhouse_text:'Выбранная продукция и решения для защищенного грунта.', irrigation:'Орошение и оборудование', irrigation_text:'Оборудование и решения для управления водными ресурсами и сельскохозяйственных систем.', sourcing:'Индивидуальный поиск', sourcing_text:'Сообщите, что вам требуется, и мы оценим возможности поиска и поставки.', quote:'Запросить предложение', info:'Запросить информацию', inquiry:'Начать запрос',
      engineering_title:'Практический сельскохозяйственный инжиниринг.', engineering_text2:'Техническая поддержка аграрных проектов, производственных систем и инфраструктурных задач.', greenhouse_dev:'Развитие тепличных систем', project_plan:'Планирование аграрных проектов', irrigation_sol:'Решения по орошению', production:'Производственные системы', assessment:'Техническая оценка', consulting:'Консалтинг',
      projects_title:'От технической задачи к практическому решению.', projects_text:'Проверенные проекты будут представлены в формате кейсов по мере появления подтвержденной информации.', case_framework:'СТРУКТУРА КЕЙСА', context:'Место и контекст', challenge:'Задача и решение', results:'Результаты и доказательства',
      markets_title:'Рынки, которые мы соединяем.', market_note:'Указанные рынки являются направлениями коммерческого интереса и не означают подтвержденную деятельность без соответствующих доказательств.', iran:'Иран', uzbekistan:'Узбекистан', turkiye:'Турция', iraq:'Ирак',
      network_title:'Zarus — сельскохозяйственная сеть поставок', network_text:'Zarus развивается как связанная аграрная платформа, соединяющая поставщиков и сельскохозяйственных покупателей.', suppliers:'Поставщики', customers:'Аграрные покупатели', network_link:'Узнать больше о развивающейся модели Zarus.',
      why_title:'Техническое мышление за коммерческими возможностями.', experience:'Технический опыт', knowledge:'Аграрная экспертиза', network:'Связи с поставщиками', outlook:'Международный взгляд',
      about_title:'Технические знания. Аграрная экспертиза. Международный взгляд.', about_text:'Agro-Zia развивается как B2B-платформа, соединяющая аграрную продукцию, техническую экспертизу и рыночные возможности.', partnerships:'Деловые партнерства',
      knowledge_title:'Практические аграрные знания.', knowledge_text:'Будущий центр технической информации, рыночных обзоров и материалов по сельскому хозяйству.', technology:'Аграрные технологии', fertilizers:'Удобрения', greenhouse_management:'Управление теплицами', market_insights:'Рыночная аналитика',
      contact_title:'Расскажите, что вам требуется.', contact_text:'Если вам нужна продукция, инженерная услуга, проектный партнер или торговая связь, отправьте нам ваши требования.', name:'Имя', company:'Компания', country:'Страна', email:'Email', phone:'WhatsApp / Телефон', interest:'Интерес', message:'Сообщение', submit:'Отправить бизнес-запрос', form_note:'В этой статической версии отправка формы открывает почтовый клиент. Серверная обработка заявок может быть добавлена на следующем этапе V3.x.',
      footer_explore:'Разделы', footer_markets:'Рынки', footer_contact:'Контакты', footer_connect:'Соединяем аграрную продукцию, экспертизу и рынки.'
    },
    fa: {
      nav_home:'خانه', nav_about:'درباره ما', nav_products:'محصولات', nav_engineering:'مهندسی', nav_projects:'پروژه‌ها', nav_trade:'تجارت', nav_knowledge:'دانش', nav_contact:'تماس',
      eyebrow:'کشاورزی • مهندسی • تجارت بین‌المللی', hero_title:'راهکارهای کشاورزی فراتر از مرزها.', hero_lead:'محصولات کشاورزی، دانش و خدمات مهندسی و راهکارهای تجارت بین‌المللی برای اتصال تولیدکنندگان، تأمین‌کنندگان و بازارها.', hero_primary:'راهکارهای ما', hero_secondary:'ارسال درخواست تجاری',
      intro_title:'اتصال محصول، تخصص و بازار.', intro_text:'Agro-Zia به‌عنوان یک پلتفرم حرفه‌ای B2B برای محصولات کشاورزی، خدمات فنی، پروژه‌ها و ارتباطات تجاری بین‌المللی در حال توسعه است.',
      business_eyebrow:'کسب‌وکار ما', business_title:'چهار توانمندی؛ یک پلتفرم کسب‌وکار کشاورزی.', business_text:'ما محصولات، تخصص فنی، توسعه پروژه و فرصت‌های بازار را حول نیازهای واقعی کشاورزی به یکدیگر متصل می‌کنیم.',
      products:'محصولات کشاورزی', products_text:'کودها، نهاده‌های کشاورزی، محصولات تولیدی و گروه‌های منتخب تأمین برای خریداران حرفه‌ای.', engineering:'مهندسی', engineering_text:'ارزیابی فنی، برنامه‌ریزی، آبیاری، گلخانه و راهکارهای تولید کشاورزی.', projects:'پروژه‌ها', projects_text:'برنامه‌ریزی، هماهنگی فنی و نظارت بر پروژه با پشتیبانی متخصصان و شرکای مناسب.', trade:'تجارت بین‌المللی', trade_text:'تأمین‌یابی، ارتباط فروشنده و خریدار و توسعه بازار در فرصت‌های منطقه‌ای و بین‌المللی.',
      products_title:'گروه‌های منتخب تأمین برای خریداران حرفه‌ای.', products_note:'اطلاعات محصول و قیمت‌گذاری از طریق درخواست تجاری و پس از بررسی اطلاعات تأمین ارائه می‌شود.', fertilizer:'کودها', fertilizer_text:'گروه‌ها و فرمولاسیون‌های کود متناسب با محصول، خاک و نیاز بازار.', inputs:'نهاده‌های کشاورزی', inputs_text:'نهاده‌های موردنیاز عملیات کشاورزی، مشروط به بررسی محصول و موجودی.', ag_products:'محصولات کشاورزی', ag_products_text:'سبد در حال توسعه‌ای از محصولات برای شرکای تجاری داخلی و بین‌المللی.', greenhouse:'محصولات گلخانه‌ای', greenhouse_text:'محصولات و راهکارهای منتخب برای کشاورزی در محیط کنترل‌شده.', irrigation:'آبیاری و تجهیزات', irrigation_text:'تجهیزات و راهکارهای مدیریت آب و سامانه‌های تولید کشاورزی.', sourcing:'تأمین سفارشی', sourcing_text:'نیاز خود را اعلام کنید تا امکان تأمین و تهیه آن را بررسی کنیم.', quote:'درخواست قیمت', info:'درخواست اطلاعات', inquiry:'شروع درخواست',
      engineering_title:'مهندسی کشاورزی با تمرکز بر راهکارهای عملی.', engineering_text2:'پشتیبانی فنی برای پروژه‌های کشاورزی، سامانه‌های تولید و نیازهای زیرساختی.', greenhouse_dev:'توسعه گلخانه', project_plan:'برنامه‌ریزی پروژه‌های کشاورزی', irrigation_sol:'راهکارهای آبیاری', production:'سامانه‌های تولید', assessment:'ارزیابی فنی', consulting:'مشاوره',
      projects_title:'از چالش فنی تا راهکار عملی.', projects_text:'پروژه‌های منتخب پس از تأیید اطلاعات در قالب مطالعات موردی ارائه خواهند شد.', case_framework:'چارچوب مطالعه موردی', context:'مکان و زمینه پروژه', challenge:'چالش و راهکار', results:'نتایج و شواهد',
      markets_title:'بازارهایی که به یکدیگر متصل می‌کنیم.', market_note:'این بازارها به‌عنوان حوزه‌های مورد علاقه تجاری معرفی می‌شوند و تا زمان احراز شواهد، ادعای فعالیت مستقر محسوب نمی‌شوند.', iran:'ایران', uzbekistan:'ازبکستان', turkiye:'ترکیه', iraq:'عراق',
      network_title:'Zarus — شبکه تأمین کشاورزی', network_text:'Zarus به‌عنوان یک شبکه تأمین کشاورزی در حال توسعه است که تأمین‌کنندگان و مشتریان کشاورزی را به یکدیگر متصل می‌کند.', suppliers:'تأمین‌کنندگان', customers:'مشتریان کشاورزی', network_link:'مدل در حال توسعه Zarus و شبکه تأمین آن را ببینید.',
      why_title:'تفکر فنی در پشت فرصت‌های تجاری.', experience:'تجربه فنی', knowledge:'نگاه کشاورزی', network:'ارتباط با تأمین‌کنندگان', outlook:'نگاه بین‌المللی',
      about_title:'دانش فنی. نگاه کشاورزی. چشم‌انداز بین‌المللی.', about_text:'Agro-Zia به‌عنوان یک پلتفرم B2B برای اتصال محصولات کشاورزی، تخصص فنی و فرصت‌های بازار در حال توسعه است.', partnerships:'مشارکت‌های تجاری',
      knowledge_title:'دانش کاربردی کشاورزی.', knowledge_text:'مرکز آینده Agro-Zia برای اطلاعات فنی، بینش بازار و موضوعات کشاورزی.', technology:'فناوری کشاورزی', fertilizers:'کودها', greenhouse_management:'مدیریت گلخانه', market_insights:'بینش بازار',
      contact_title:'نیاز خود را با ما در میان بگذارید.', contact_text:'اگر به محصول، خدمات مهندسی، شریک پروژه یا ارتباط تجاری نیاز دارید، نیازمندی خود را ارسال کنید.', name:'نام', company:'شرکت', country:'کشور', email:'ایمیل', phone:'واتساپ / تلفن', interest:'موضوع درخواست', message:'پیام', submit:'ارسال درخواست تجاری', form_note:'در این نسخه استاتیک، ارسال فرم برنامه ایمیل را باز می‌کند. امکان افزودن سامانه ثبت درخواست در نسخه بعدی V3.x وجود دارد.',
      footer_explore:'دسترسی سریع', footer_markets:'بازارها', footer_contact:'تماس', footer_connect:'اتصال محصولات کشاورزی، تخصص و بازارها.'
    },
    ar: {
      nav_home:'الرئيسية', nav_about:'من نحن', nav_products:'المنتجات', nav_engineering:'الهندسة', nav_projects:'المشاريع', nav_trade:'التجارة', nav_knowledge:'المعرفة', nav_contact:'اتصل بنا',
      eyebrow:'الزراعة • الهندسة • التجارة الدولية', hero_title:'حلول زراعية تتجاوز الحدود.', hero_lead:'منتجات زراعية وخبرة هندسية وحلول للتجارة الدولية تربط المنتجين والموردين والأسواق.', hero_primary:'استكشف حلولنا', hero_secondary:'ابدأ استفساراً تجارياً',
      intro_title:'نربط المنتجات والخبرة والأسواق.', intro_text:'يتم تطوير Agro-Zia كمنصة B2B مهنية للمنتجات الزراعية والخدمات الفنية والمشاريع والعلاقات التجارية الدولية.',
      business_eyebrow:'أعمالنا', business_title:'أربع قدرات. منصة أعمال زراعية واحدة.', business_text:'نربط المنتجات والخبرة الفنية وتطوير المشاريع وفرص الأسواق حول الاحتياجات العملية للقطاع الزراعي.',
      products:'المنتجات الزراعية', products_text:'أسمدة ومدخلات زراعية ومنتجات إنتاج وفئات توريد مختارة للمشترين المحترفين.', engineering:'الهندسة', engineering_text:'تقييم فني وتخطيط وري وبيوت محمية وحلول للإنتاج الزراعي.', projects:'المشاريع', projects_text:'تخطيط المشاريع والتنسيق والإشراف الفني بدعم من المختصين والشركاء المناسبين.', trade:'التجارة الدولية', trade_text:'تأمين المنتجات وربط الموردين بالمشترين وتطوير الأسواق إقليمياً ودولياً.',
      products_title:'فئات توريد مختارة للمشترين المحترفين.', products_note:'يتم تقديم معلومات المنتجات وعروض الأسعار عبر الاستفسارات التجارية وبعد التحقق من بيانات التوريد.', fertilizer:'الأسمدة', fertilizer_text:'فئات وتركيبات الأسمدة وفقاً للمحصول والتربة ومتطلبات السوق.', inputs:'المدخلات الزراعية', inputs_text:'مدخلات لعمليات الإنتاج الزراعي مع مراعاة التحقق من المنتج وتوفره.', ag_products:'المنتجات الزراعية', ag_products_text:'مجموعة متنامية من المنتجات للشركاء التجاريين المحليين والدوليين.', greenhouse:'منتجات البيوت المحمية', greenhouse_text:'منتجات وحلول مختارة للزراعة المحمية.', irrigation:'الري والمعدات', irrigation_text:'معدات وحلول لإدارة المياه والأنظمة الزراعية.', sourcing:'تأمين مخصص', sourcing_text:'أخبرنا بما تحتاجه وسنقيّم فرص التأمين والتوريد.', quote:'طلب عرض سعر', info:'طلب معلومات', inquiry:'ابدأ استفساراً',
      engineering_title:'هندسة زراعية تركز على الحلول العملية.', engineering_text2:'دعم فني للمشاريع الزراعية وأنظمة الإنتاج والاحتياجات الأساسية.', greenhouse_dev:'تطوير البيوت المحمية', project_plan:'تخطيط المشاريع الزراعية', irrigation_sol:'حلول الري', production:'أنظمة الإنتاج', assessment:'التقييم الفني', consulting:'الاستشارات',
      projects_title:'من التحدي الفني إلى الحل العملي.', projects_text:'سيتم عرض المشاريع المختارة كدراسات حالة عند توفر معلومات موثقة.', case_framework:'إطار دراسة الحالة', context:'الموقع والسياق', challenge:'التحدي والحل', results:'النتائج والأدلة',
      markets_title:'الأسواق التي نربطها.', market_note:'تمثل هذه الأسواق مجالات اهتمام تجاري ولا تعني وجود عمليات قائمة ما لم يتم التحقق منها.', iran:'إيران', uzbekistan:'أوزبكستان', turkiye:'تركيا', iraq:'العراق',
      network_title:'Zarus — شبكة التوريد الزراعي', network_text:'تتطور Zarus كمنصة توريد زراعي تربط الموردين بالعملاء الزراعيين.', suppliers:'الموردون', customers:'العملاء الزراعيون', network_link:'استكشف نموذج Zarus وشبكة التوريد المتطورة.',
      why_title:'التفكير الفني وراء الفرص التجارية.', experience:'الخبرة الفنية', knowledge:'الرؤية الزراعية', network:'علاقات الموردين', outlook:'الرؤية الدولية',
      about_title:'معرفة فنية. منظور زراعي. رؤية دولية.', about_text:'يتم تطوير Agro-Zia كمنصة B2B تربط المنتجات الزراعية والخبرة الفنية وفرص الأسواق.', partnerships:'الشراكات التجارية',
      knowledge_title:'معرفة زراعية عملية.', knowledge_text:'مركز معرفة مستقبلي للمعلومات الفنية ورؤى الأسواق والموضوعات الزراعية.', technology:'التقنية الزراعية', fertilizers:'الأسمدة', greenhouse_management:'إدارة البيوت المحمية', market_insights:'رؤى الأسواق',
      contact_title:'أخبرنا بما تبحث عنه.', contact_text:'إذا كنت تحتاج إلى منتج أو خدمة هندسية أو شريك مشروع أو اتصال تجاري، أرسل متطلباتك.', name:'الاسم', company:'الشركة', country:'الدولة', email:'البريد الإلكتروني', phone:'واتساب / الهاتف', interest:'الاهتمام', message:'الرسالة', submit:'إرسال الاستفسار التجاري', form_note:'في هذه النسخة الثابتة، يؤدي إرسال النموذج إلى فتح برنامج البريد الإلكتروني. يمكن إضافة نظام استقبال طلبات خادمي في مرحلة V3.x لاحقاً.',
      footer_explore:'استكشف', footer_markets:'الأسواق', footer_contact:'اتصل بنا', footer_connect:'ربط المنتجات الزراعية والخبرة والأسواق.'
    },
    uz: {
      nav_home:'Bosh sahifa', nav_about:'Biz haqimizda', nav_products:'Mahsulotlar', nav_engineering:'Muhandislik', nav_projects:'Loyihalar', nav_trade:'Savdo', nav_knowledge:'Bilim', nav_contact:'Aloqa',
      eyebrow:'QISHLOQ XO‘JALIGI • MUHANDISLIK • XALQARO SAVDO', hero_title:'Chegaralardan tashqari qishloq xo‘jaligi yechimlari.', hero_lead:'Ishlab chiqaruvchilar, yetkazib beruvchilar va bozorlarni bog‘laydigan qishloq xo‘jaligi mahsulotlari, muhandislik tajribasi va xalqaro savdo yechimlari.', hero_primary:'Yechimlarimiz', hero_secondary:'Biznes so‘rovi yuborish',
      intro_title:'Mahsulot, tajriba va bozorlarni bog‘laymiz.', intro_text:'Agro-Zia qishloq xo‘jaligi mahsulotlari, texnik xizmatlar, loyihalar va xalqaro biznes aloqalari uchun professional B2B platforma sifatida rivojlantirilmoqda.',
      business_eyebrow:'BIZNING BIZNES', business_title:'To‘rt yo‘nalish. Bitta qishloq xo‘jaligi biznes platformasi.', business_text:'Biz mahsulotlar, texnik tajriba, loyiha rivoji va bozor imkoniyatlarini amaliy qishloq xo‘jaligi ehtiyojlari atrofida bog‘laymiz.',
      products:'Qishloq xo‘jaligi mahsulotlari', products_text:'Professional xaridorlar uchun o‘g‘itlar, qishloq xo‘jaligi vositalari va tanlangan ta’minot toifalari.', engineering:'Muhandislik', engineering_text:'Texnik baholash, rejalashtirish, sug‘orish, issiqxona va ishlab chiqarish yechimlari.', projects:'Loyihalar', projects_text:'Mutaxassislar va hamkorlar ko‘magida loyihalarni rejalashtirish, texnik muvofiqlashtirish va nazorat.', trade:'Xalqaro savdo', trade_text:'Ta’minot izlash, yetkazib beruvchi va xaridorlarni bog‘lash hamda mintaqaviy va xalqaro bozorlarni rivojlantirish.',
      products_title:'Professional xaridorlar uchun tanlangan ta’minot toifalari.', products_note:'Mahsulot ma’lumotlari va takliflar biznes so‘rovlari hamda tekshirilgan ta’minot ma’lumotlari asosida taqdim etiladi.', fertilizer:'O‘g‘itlar', fertilizer_text:'Ekin, tuproq va bozor talablariga mos o‘g‘it toifalari va formulalari.', inputs:'Qishloq xo‘jaligi vositalari', inputs_text:'Mavjudligi va mahsulot tekshiruvi asosida qishloq xo‘jaligi ishlab chiqarish vositalari.', ag_products:'Qishloq xo‘jaligi mahsulotlari', ag_products_text:'Mahalliy va xalqaro tijoriy hamkorlar uchun rivojlanayotgan mahsulot portfeli.', greenhouse:'Issiqxona mahsulotlari', greenhouse_text:'Himoyalangan qishloq xo‘jaligi uchun tanlangan mahsulot va yechimlar.', irrigation:'Sug‘orish va uskunalar', irrigation_text:'Suv boshqaruvi va qishloq xo‘jaligi tizimlari uchun uskunalar va yechimlar.', sourcing:'Maxsus ta’minot', sourcing_text:'Kerakli mahsulotni ayting — ta’minot imkoniyatlarini baholaymiz.', quote:'Narx so‘rash', info:'Ma’lumot so‘rash', inquiry:'So‘rov boshlash',
      engineering_title:'Amaliy yo‘nalishga ega qishloq xo‘jaligi muhandisligi.', engineering_text2:'Qishloq xo‘jaligi loyihalari, ishlab chiqarish tizimlari va infratuzilma ehtiyojlari uchun texnik yordam.', greenhouse_dev:'Issiqxonalarni rivojlantirish', project_plan:'Qishloq xo‘jaligi loyihalarini rejalashtirish', irrigation_sol:'Sug‘orish yechimlari', production:'Ishlab chiqarish tizimlari', assessment:'Texnik baholash', consulting:'Konsalting',
      projects_title:'Texnik muammodan amaliy yechimgacha.', projects_text:'Tasdiqlangan ma’lumotlar mavjud bo‘lgach, tanlangan loyihalar case-study sifatida taqdim etiladi.', case_framework:'CASE-STUDY TUZILMASI', context:'Joylashuv va kontekst', challenge:'Muammo va yechim', results:'Natijalar va dalillar',
      markets_title:'Biz bog‘laydigan bozorlar.', market_note:'Bozorlar tijoriy qiziqish yo‘nalishlari sifatida ko‘rsatilgan; tasdiqlanmagan holda faoliyat mavjudligi da’vo qilinmaydi.', iran:'Eron', uzbekistan:'O‘zbekiston', turkiye:'Turkiya', iraq:'Iroq',
      network_title:'Zarus — Qishloq xo‘jaligi ta’minot tarmog‘i', network_text:'Zarus yetkazib beruvchilar va qishloq xo‘jaligi mijozlarini bog‘lovchi ta’minot platformasi sifatida rivojlanmoqda.', suppliers:'Yetkazib beruvchilar', customers:'Qishloq xo‘jaligi mijozlari', network_link:'Zarusning rivojlanayotgan modelini ko‘ring.',
      why_title:'Tijoriy imkoniyatlar ortidagi texnik fikrlash.', experience:'Texnik tajriba', knowledge:'Qishloq xo‘jaligi nuqtayi nazari', network:'Yetkazib beruvchi aloqalari', outlook:'Xalqaro qarash',
      about_title:'Texnik bilim. Qishloq xo‘jaligi qarashi. Xalqaro nuqtayi nazar.', about_text:'Agro-Zia qishloq xo‘jaligi mahsulotlari, texnik tajriba va bozor imkoniyatlarini bog‘lovchi B2B platforma sifatida rivojlantirilmoqda.', partnerships:'Biznes hamkorliklari',
      knowledge_title:'Amaliy qishloq xo‘jaligi bilimi.', knowledge_text:'Texnik ma’lumotlar, bozor tahlili va qishloq xo‘jaligi mavzulari uchun kelajakdagi bilim markazi.', technology:'Qishloq xo‘jaligi texnologiyasi', fertilizers:'O‘g‘itlar', greenhouse_management:'Issiqxona boshqaruvi', market_insights:'Bozor tahlili',
      contact_title:'Nimani izlayotganingizni ayting.', contact_text:'Mahsulot, muhandislik xizmati, loyiha hamkori yoki savdo aloqasi kerak bo‘lsa, talablaringizni yuboring.', name:'Ism', company:'Kompaniya', country:'Mamlakat', email:'Email', phone:'WhatsApp / Telefon', interest:'Qiziqish', message:'Xabar', submit:'Biznes so‘rovini yuborish', form_note:'Ushbu dastlabki statik versiyada forma yuborilganda email dasturi ochiladi. Server tomonidagi murojaat tizimi keyingi V3.x bosqichida qo‘shilishi mumkin.',
      footer_explore:'Bo‘limlar', footer_markets:'Bozorlar', footer_contact:'Aloqa', footer_connect:'Qishloq xo‘jaligi mahsulotlari, tajriba va bozorlarni bog‘laymiz.'
    },
    tr: {
      nav_home:'Ana Sayfa', nav_about:'Hakkımızda', nav_products:'Ürünler', nav_engineering:'Mühendislik', nav_projects:'Projeler', nav_trade:'Ticaret', nav_knowledge:'Bilgi', nav_contact:'İletişim',
      eyebrow:'TARIM • MÜHENDİSLİK • ULUSLARARASI TİCARET', hero_title:'Sınırların ötesinde tarım çözümleri.', hero_lead:'Üreticileri, tedarikçileri ve pazarları buluşturan tarım ürünleri, mühendislik uzmanlığı ve uluslararası ticaret çözümleri.', hero_primary:'Çözümlerimizi İnceleyin', hero_secondary:'Ticari Talep Başlatın',
      intro_title:'Ürünleri, uzmanlığı ve pazarları buluşturuyoruz.', intro_text:'Agro-Zia; tarım ürünleri, teknik hizmetler, projeler ve uluslararası iş bağlantıları için profesyonel bir B2B platform olarak geliştirilmektedir.',
      business_eyebrow:'İŞİMİZ', business_title:'Dört yetkinlik. Tek tarım iş platformu.', business_text:'Ürünleri, teknik uzmanlığı, proje geliştirmeyi ve pazar fırsatlarını pratik tarımsal ihtiyaçlar etrafında birleştiriyoruz.',
      products:'Tarım Ürünleri', products_text:'Profesyonel alıcılar için gübreler, tarımsal girdiler ve seçilmiş tedarik kategorileri.', engineering:'Mühendislik', engineering_text:'Teknik değerlendirme, planlama, sulama, sera ve tarımsal üretim çözümleri.', projects:'Projeler', projects_text:'Uygun uzmanlar ve ortakların desteğiyle proje planlama, teknik koordinasyon ve denetim.', trade:'Uluslararası Ticaret', trade_text:'Tedarik, satıcı-alıcı bağlantıları ve bölgesel ve uluslararası pazarlarda geliştirme.',
      products_title:'Profesyonel alıcılar için seçilmiş tedarik kategorileri.', products_note:'Ürün bilgileri ve teklifler ticari talepler ve doğrulanmış tedarik bilgileri üzerinden sunulur.', fertilizer:'Gübreler', fertilizer_text:'Ürün, toprak ve pazar ihtiyaçlarına göre seçilen gübre kategorileri ve formülasyonları.', inputs:'Tarımsal Girdiler', inputs_text:'Ürün doğrulaması ve bulunabilirliğe bağlı tarımsal üretim girdileri.', ag_products:'Tarım Ürünleri', ag_products_text:'Yerli ve uluslararası ticari ortaklar için gelişen ürün portföyü.', greenhouse:'Sera Ürünleri', greenhouse_text:'Örtü altı tarım için seçilmiş ürün ve çözümler.', irrigation:'Sulama ve Ekipman', irrigation_text:'Su yönetimi ve tarımsal üretim sistemleri için ekipman ve çözümler.', sourcing:'Özel Tedarik', sourcing_text:'İhtiyacınızı bildirin; tedarik ve temin olanaklarını değerlendirelim.', quote:'Teklif İste', info:'Bilgi İste', inquiry:'Talep Başlat',
      engineering_title:'Pratik odaklı tarım mühendisliği.', engineering_text2:'Tarım projeleri, üretim sistemleri ve altyapı ihtiyaçları için teknik destek.', greenhouse_dev:'Sera Geliştirme', project_plan:'Tarım Projesi Planlama', irrigation_sol:'Sulama Çözümleri', production:'Üretim Sistemleri', assessment:'Teknik Değerlendirme', consulting:'Danışmanlık',
      projects_title:'Teknik zorluktan pratik çözüme.', projects_text:'Doğrulanmış proje bilgileri hazır oldukça seçilmiş projeler vaka çalışmaları olarak sunulacaktır.', case_framework:'VAKA ÇALIŞMASI ÇERÇEVESİ', context:'Konum ve Bağlam', challenge:'Sorun ve Çözüm', results:'Sonuçlar ve Kanıtlar',
      markets_title:'Bağladığımız pazarlar.', market_note:'Pazarlar ticari ilgi alanları olarak sunulmaktadır; doğrulanmadıkça mevcut operasyon iddiası değildir.', iran:'İran', uzbekistan:'Özbekistan', turkiye:'Türkiye', iraq:'Irak',
      network_title:'Zarus — Tarımsal Tedarik Ağı', network_text:'Zarus, tedarikçileri ve tarımsal müşterileri buluşturan bağlantılı bir tedarik platformu olarak geliştirilmektedir.', suppliers:'Tedarikçiler', customers:'Tarımsal Müşteriler', network_link:'Zarus’un gelişen modelini inceleyin.',
      why_title:'Ticari fırsatların arkasındaki teknik düşünce.', experience:'Teknik Deneyim', knowledge:'Tarımsal Bakış', network:'Tedarikçi Bağlantıları', outlook:'Uluslararası Bakış',
      about_title:'Teknik bilgi. Tarımsal bakış. Uluslararası perspektif.', about_text:'Agro-Zia, tarım ürünlerini, teknik uzmanlığı ve pazar fırsatlarını birbirine bağlayan bir B2B platform olarak geliştirilmektedir.', partnerships:'İş Ortaklıkları',
      knowledge_title:'Pratik tarımsal bilgi.', knowledge_text:'Teknik bilgiler, pazar içgörüleri ve tarım konuları için gelecekteki bilgi merkezi.', technology:'Tarım Teknolojisi', fertilizers:'Gübreler', greenhouse_management:'Sera Yönetimi', market_insights:'Pazar İçgörüleri',
      contact_title:'Aradığınızı bize anlatın.', contact_text:'Bir ürüne, mühendislik hizmetine, proje ortağına veya ticari bağlantıya ihtiyacınız varsa gereksinimlerinizi gönderin.', name:'Ad', company:'Şirket', country:'Ülke', email:'E-posta', phone:'WhatsApp / Telefon', interest:'İlgi Alanı', message:'Mesaj', submit:'Ticari Talep Gönder', form_note:'Bu ilk statik sürümde form gönderimi e-posta istemcinizi açar. Sunucu taraflı talep sistemi sonraki V3.x aşamasında eklenebilir.',
      footer_explore:'Keşfet', footer_markets:'Pazarlar', footer_contact:'İletişim', footer_connect:'Tarım ürünlerini, uzmanlığı ve pazarları buluşturuyoruz.'
    }
  };

  function getLang(){ const q=new URLSearchParams(location.search).get('lang'); return languages[q] ? q : 'en'; }
  function apply(lang){
    const active=languages[lang] ? lang : 'en';
    document.documentElement.lang=active;
    document.documentElement.dir=languages[active].dir;
    document.body.dataset.language=active;
    document.querySelectorAll('[data-i18n]').forEach(el=>{
      const key=el.dataset.i18n;
      if(t[active][key] !== undefined) el.textContent=t[active][key];
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{
      const key=el.dataset.i18nPlaceholder;
      if(t[active][key] !== undefined) el.placeholder=t[active][key];
    });
    document.querySelectorAll('[data-lang-link]').forEach(a=>{
      const code=a.dataset.langLink;
      const url=new URL(location.href); url.searchParams.set('lang',code); a.href=url.pathname+'?'+url.searchParams.toString().replace(/^\?/,'')+url.hash;
      a.setAttribute('aria-current',code===active?'true':'false');
    });
    const label=document.querySelector('[data-lang-current]'); if(label) label.textContent=languages[active].short;
    localStorage.setItem('agro-zia-lang',active);
  }
  function init(){
    const saved=localStorage.getItem('agro-zia-lang');
    const lang=new URLSearchParams(location.search).get('lang') || (languages[saved]?saved:'en');
    apply(lang);
    const button=document.querySelector('[data-lang-button]'), box=document.querySelector('[data-lang-menu]');
    if(button && box){
      button.addEventListener('click',()=>{const open=box.parentElement.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));});
      document.addEventListener('click',e=>{if(!box.parentElement.contains(e.target)){box.parentElement.classList.remove('is-open');button.setAttribute('aria-expanded','false');}});
    }
  }
  window.AgroZiaI18n={languages,t,apply};
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init); else init();
})();
