import {
  canAttemptChallenge,
  challengeExpiresAt,
  clearCustomerSessionCookie,
  createCustomerSession,
  hashLoginCode,
  isChallengeExpired,
  normalizeCustomerEmail,
  customerSessionCookie,
  readCustomerSession,
} from "./customer-auth.js";

const CODE_TTL_MINUTES = 10;
const CODE_RE = /^\d{6}$/;

function json(data, status = 200, headers = {}) {
  return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=UTF-8", "cache-control": "no-store", ...headers } });
}
function bodyTooLarge(request) { return Number(request.headers.get("content-length") || 0) > 16 * 1024; }
async function parseJson(request) { if (bodyTooLarge(request)) throw new Error("body_too_large"); try { return await request.json(); } catch (_) { throw new Error("invalid_json"); } }
function randomCode() { return String(Math.floor(100000 + Math.random() * 900000)); }
async function findOrCreateAccount(db, email, profile = {}) { let account = await db.prepare("SELECT id,email,name,company,phone,country,status,created_at,updated_at,last_login_at FROM customer_accounts WHERE email = ? LIMIT 1").bind(email).first(); const now = new Date().toISOString(); if (!account) { const id = crypto.randomUUID(); await db.prepare("INSERT INTO customer_accounts (id,email,name,company,phone,country,status,created_at,updated_at) VALUES (?,?,?,?,?,?, 'active', ?, ?)").bind(id,email,profile.name||null,profile.company||null,profile.phone||null,profile.country||null,now,now).run(); account = await db.prepare("SELECT id,email,name,company,phone,country,status,created_at,updated_at,last_login_at FROM customer_accounts WHERE id = ? LIMIT 1").bind(id).first(); } return account; }
async function sendLoginCode(env,email,code) { if (!env.EMAIL) return false; await env.EMAIL.send({to:email,from:"export@agro-zia.com",subject:"Your ZARUS customer sign-in code",text:`Your ZARUS sign-in code is ${code}. It expires in ${CODE_TTL_MINUTES} minutes. If you did not request this code, you can ignore this email.`}); return true; }
async function requestLogin(request,env) { if(!env.AGROZIA_DB)return json({error:"d1_unavailable"},503); const input=await parseJson(request),email=normalizeCustomerEmail(input?.email); if(!email)return json({error:"invalid_email"},400); const account=await findOrCreateAccount(env.AGROZIA_DB,email,input); if(account.status!=="active")return json({ok:true,message:"If this email can sign in, a code has been sent."}); const code=randomCode(),id=crypto.randomUUID(),now=new Date().toISOString(),expires=challengeExpiresAt(),codeHash=await hashLoginCode(code,id); await env.AGROZIA_DB.prepare("UPDATE customer_login_challenges SET consumed_at = ? WHERE email = ? AND consumed_at IS NULL").bind(now,email).run(); await env.AGROZIA_DB.prepare("INSERT INTO customer_login_challenges (id,account_id,email,code_hash,expires_at,attempts,created_at) VALUES (?,?,?,?,?,0,?)").bind(id,account.id,email,codeHash,expires,now).run(); try { const sent=await sendLoginCode(env,email,code); if(!sent)return json({error:"email_unconfigured"},503); } catch(_){return json({error:"email_send_failed"},503);} return json({ok:true,message:"If this email can sign in, a code has been sent."}); }
async function verifyLogin(request,env) { if(!env.AGROZIA_DB)return json({error:"d1_unavailable"},503); const input=await parseJson(request),email=normalizeCustomerEmail(input?.email),code=String(input?.code||"").trim(); if(!email||!CODE_RE.test(code))return json({error:"invalid_code"},400); const challenge=await env.AGROZIA_DB.prepare("SELECT id,account_id,email,code_hash,expires_at,attempts FROM customer_login_challenges WHERE email = ? AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1").bind(email).first(); if(!challenge||isChallengeExpired(challenge.expires_at)||!canAttemptChallenge(challenge.attempts))return json({error:"invalid_code"},401); const suppliedHash=await hashLoginCode(code,challenge.id); if(suppliedHash!==challenge.code_hash){await env.AGROZIA_DB.prepare("UPDATE customer_login_challenges SET attempts = attempts + 1 WHERE id = ?").bind(challenge.id).run();return json({error:"invalid_code"},401);} const now=new Date().toISOString(),account=await env.AGROZIA_DB.prepare("SELECT id,email,name,company,phone,country,status,created_at,updated_at,last_login_at FROM customer_accounts WHERE id = ? LIMIT 1").bind(challenge.account_id).first(); if(!account||account.status!=="active")return json({error:"account_unavailable"},403); await env.AGROZIA_DB.prepare("UPDATE customer_login_challenges SET consumed_at = ? WHERE id = ?").bind(now,challenge.id).run(); await env.AGROZIA_DB.prepare("UPDATE customer_accounts SET last_login_at = ?, updated_at = ? WHERE id = ?").bind(now,now,account.id).run(); const token=await createCustomerSession(env,account.id); if(!token)return json({error:"customer_auth_unconfigured"},503); return json({ok:true,account:publicAccount(account)},200,{"set-cookie":customerSessionCookie(token)}); }
function publicAccount(account){return{id:account.id,email:account.email,name:account.name||null,company:account.company||null,phone:account.phone||null,country:account.country||null};}
async function requireCustomer(request,env){const session=await readCustomerSession(request,env);if(!session||!env.AGROZIA_DB)return null;const account=await env.AGROZIA_DB.prepare("SELECT id,email,name,company,phone,country,status,created_at,updated_at,last_login_at FROM customer_accounts WHERE id = ? LIMIT 1").bind(session.accountId).first();return account?.status==="active"?account:null;}
function mapRfq(row){return{id:row.id,request_number:row.request_number,status:row.status,product_id:row.product_id,product_name:row.product_name,supplier_id:row.supplier_id,supplier_name:row.supplier_name||null,quantity:row.quantity,destination_country:row.destination_country,destination_location:row.destination_location,created_at:row.created_at,updated_at:row.updated_at};}
async function listRfqs(db,account){const rows=await db.prepare(`SELECT r.id,r.request_number,r.status,r.product_id,r.product_name,r.supplier_id,s.name AS supplier_name,r.quantity,r.destination_country,r.destination_location,r.created_at,r.updated_at FROM commerce_rfqs r LEFT JOIN commerce_suppliers s ON s.id = r.supplier_id WHERE r.customer_account_id = ? OR (r.customer_account_id IS NULL AND LOWER(COALESCE(r.buyer_email,'')) = ?) ORDER BY r.created_at DESC LIMIT 100`).bind(account.id,account.email).all();return(rows.results||[]).map(mapRfq);}
async function listQuotes(db,account){const rows=await db.prepare(`SELECT q.id,q.quote_number,q.rfq_id,q.supplier_id,s.name AS supplier_name,q.product_id,q.product_name,q.quantity,q.currency,q.unit_price_minor,q.total_amount_minor,q.lead_time,q.validity_until,q.payment_terms,q.incoterm,q.destination,q.status,q.created_at,q.updated_at FROM commerce_quotes q JOIN commerce_rfqs r ON r.id = q.rfq_id LEFT JOIN commerce_suppliers s ON s.id = q.supplier_id WHERE r.customer_account_id = ? OR (r.customer_account_id IS NULL AND LOWER(COALESCE(r.buyer_email,'')) = ?) ORDER BY q.created_at DESC LIMIT 100`).bind(account.id,account.email).all();return rows.results||[];}
async function listOrders(db,account){const rows=await db.prepare(`SELECT o.id,o.order_number,o.quote_id,o.rfq_id,o.supplier_id,s.name AS supplier_name,o.product_id,o.product_name,o.quantity,o.currency,o.unit_price_minor,o.quoted_amount_minor,o.destination,o.status,o.created_at,o.updated_at FROM commerce_orders o JOIN commerce_rfqs r ON r.id = o.rfq_id LEFT JOIN commerce_suppliers s ON s.id = o.supplier_id WHERE r.customer_account_id = ? OR (r.customer_account_id IS NULL AND LOWER(COALESCE(r.buyer_email,'')) = ?) ORDER BY o.created_at DESC LIMIT 100`).bind(account.id,account.email).all();return rows.results||[];}
async function workspace(request,env){const account=await requireCustomer(request,env);if(!account)return json({error:"customer_unauthorized"},401);const[rfqs,quotes,orders]=await Promise.all([listRfqs(env.AGROZIA_DB,account),listQuotes(env.AGROZIA_DB,account),listOrders(env.AGROZIA_DB,account)]);return json({account:publicAccount(account),rfqs,quotes,orders});}
async function logout(){return json({ok:true},200,{"set-cookie":clearCustomerSessionCookie()});}
export async function handleCustomerRoute(request,env){const url=new URL(request.url);if(!url.pathname.startsWith("/api/customer/"))return null;try{if(url.pathname==="/api/customer/login/request"&&request.method==="POST")return await requestLogin(request,env);if(url.pathname==="/api/customer/login/verify"&&request.method==="POST")return await verifyLogin(request,env);if(url.pathname==="/api/customer/session"&&request.method==="GET"){const account=await requireCustomer(request,env);return account?json({authenticated:true,account:publicAccount(account)}):json({authenticated:false},401);}if(url.pathname==="/api/customer/workspace"&&request.method==="GET")return await workspace(request,env);if(url.pathname==="/api/customer/logout"&&request.method==="POST")return await logout();return json({error:"not_found"},404);}catch(error){console.error("Customer API error",{code:String(error?.message||"unknown").slice(0,80)});return json({error:"customer_request_failed"},503);}}
